"""add repository files and chunks

Revision ID: 56391a6f4d62
Revises: f18c75fbcf7e
Create Date: 2026-08-15 16:25:57.816772

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56391a6f4d62'
down_revision: str | Sequence[str] | None = 'f18c75fbcf7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_file_id', sa.UUID(), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.String(length=50), nullable=False),
    sa.Column('parent_symbol', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_repository_file_id'), 'chunks', ['repository_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_repository_file_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
