"""create repository table

Revision ID: f18c75fbcf7e
Revises: 
Create Date: 2026-08-04 22:39:10.906793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18c75fbcf7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('default_branch', sa.String(length=50), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'READY', 'FAILED', name='repository_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_github_url'), 'repositories', ['github_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_github_url'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
